"use client";
import { createContext, useContext, useEffect, useState } from 'react';
const translations: Record<string,string> = {
 'เลือกรูปภาพหรือเอกสาร ·':'Choose an image or document ·','เพิ่มเมนูหลัก':'Add main menu','เพิ่มเมนูย่อยใต้ “':'Add submenu under “','เปิดลิงก์ในแท็บใหม่':'Open link in new tab','เพิ่มลิงก์ใน':'Add link to','จัดการ':'Actions','(ไม่มีชื่อ)':'(Untitled)','เพิ่มผู้ใช้':'Add user','(คุณ)':'(You)','ตั้งรหัสผ่านใหม่':'Set new password','สำหรับ @':'For @','ยืนยัน':'Confirm','สร้างอัตโนมัติ':'Generate automatically','เอารูปออกจากโปรไฟล์ (ไฟล์ยังอยู่ในคลัง)':'Remove profile image (keep file in library)','นี้':'','รูปภาพและเอกสารสำหรับเว็บไซต์ ·':'Website images and documents ·','ส่งออก CSV':'Export CSV','หมายเหตุภายใน':'Internal notes','บันทึกการตั้งค่า':'Save settings','ก่อนแก้ไข':'Before','หลังแก้ไข':'After','เพิ่มภาพ':'Add photo','ยังไม่มีประวัติการแก้ไข':'No change history yet','ก่อนหน้า':'Previous','หน้า':'Page','ถัดไป':'Next','ดูหน้าบุคลากร ↗':'View staff page ↗',
 'แก้ไขข้อความแล้วคลิกออกจากช่องเพื่อบันทึกอัตโนมัติ การเพิ่ม ลบ และเปลี่ยนลำดับมีผลทันที ใช้ปุ่มลูกศรเพื่อเลื่อนรายการขึ้นหรือลง':'Edit a field and click outside it to save automatically. Adding, deleting and reordering take effect immediately. Use the arrows to move items up or down.',
 'เพิ่มบุคลากร → ใส่ชื่อ ตำแหน่ง รูปภาพ และช่องทางติดต่อ → บันทึกเป็นฉบับร่าง → เลือกเผยแพร่เมื่อพร้อม':'Add staff → enter name, position, photo and contact details → save a draft → publish when ready.',
 'รูปภาพจะมีกรอบให้อัตโนมัติ แก้ไขหรือจัดลำดับได้จากรายการด้านล่าง ใช้เฉพาะภาพและข้อมูลติดต่อที่เจ้าของอนุญาตให้เผยแพร่':'Photos are framed automatically. Edit or reorder using the list below. Publish only photos and contact details with the owner’s permission.',
 'ภาพรวม':'Overview','แดชบอร์ด':'Dashboard','เนื้อหาหน้าเว็บ':'Website content','ข้อความในหน้า':'Page content','รายการย่อย':'Content lists','คอนเทนต์':'Content','ข่าวสาร':'News','กิจกรรม':'Activities','คณะกรรมการ':'Committee','บุคลากร':'Staff','งานวิจัย':'Research','รางวัล':'Awards','ตำแหน่งงาน':'Careers','ประมวลภาพ':'Gallery','เอกสาร':'Documents','เส้นเวลา':'Timeline','ตัวเลขสถิติ':'Statistics','การ์ดบริการ':'Service cards','สถานที่':'Locations','พันธมิตร':'Partners','ระบบ':'System','เมนูและฟุตเตอร์':'Navigation & footer','คลังไฟล์':'Media library','กล่องข้อความ':'Inbox','ตั้งค่าเว็บไซต์':'Site settings','ผู้ดูแลระบบ':'Administrator','ผู้แก้ไข':'Editor','ประวัติการแก้ไข':'Change history','ดูเว็บไซต์':'View website','ออกจากระบบ':'Sign out','ไปยังแดชบอร์ด':'Go to dashboard','เมนูผู้ดูแลระบบ':'Admin navigation',
 'ชื่อผู้ใช้':'Username','รหัสผ่าน':'Password','เข้าสู่ระบบ':'Sign in','เข้าสู่ระบบผู้ดูแล':'Admin sign in','กลับสู่เว็บไซต์':'Back to website','ทุกเรื่องราวของ RISA':'Every RISA story','เริ่มต้นได้ที่นี่':'starts here','พื้นที่สำหรับทีมงานในการเผยแพร่ข่าวสาร กิจกรรม และองค์ความรู้ของสมาคม':'A workspace for publishing the association’s news, events and knowledge.','จัดการเนื้อหาและอัปเดตเว็บไซต์ RISA':'Manage content and update the RISA website','ยังไม่มีบัญชีหรือลืมรหัสผ่าน? ติดต่อผู้ดูแลระบบของสมาคม':'Need an account or forgot your password? Contact your site administrator.',
 'พื้นที่จัดการเว็บไซต์':'Website workspace','แบ่งปันข่าวสาร อัปเดตกิจกรรม และดูแลทุกเรื่องราวของ RISA':'Share news, update events and manage RISA’s content.','เขียนข่าวใหม่':'Write news','เพิ่มหัวข้อ เนื้อหา และภาพประกอบ':'Add a headline, article and images','อัปโหลดไฟล์':'Upload files','เก็บรูปภาพและเอกสารไว้พร้อมใช้งาน':'Keep images and documents ready to use','แก้ไขหน้าเว็บไซต์':'Edit website pages','ปรับข้อความและรูปภาพในแต่ละหน้า':'Update each page’s text and images','ข้อความใหม่':'New messages','ดูทั้งหมด':'View all','ยังไม่มีข้อความใหม่':'No new messages','ประวัติการแก้ไขล่าสุด':'Recent changes',
 'บันทึก':'Save','บันทึกแล้ว':'Saved','ยกเลิก':'Cancel','ลบ':'Delete','แก้ไข':'Edit','เพิ่ม':'Add','ทำสำเนา':'Duplicate','รายละเอียด':'Details','ทั้งหมด':'All','เผยแพร่':'Published','ฉบับร่าง':'Draft','เลือกรูปภาพ':'Choose image','เลือกจากคลัง':'Choose from library','เลือกไอคอน':'Choose icon','อัปโหลด':'Upload','เลือกไฟล์':'Choose file','ปิด':'Close','รูปภาพงานวิจัย':'Research image','ชื่อผลงาน':'Title','ผู้แต่ง':'Authors','แหล่งเผยแพร่':'Publication','บทคัดย่อ':'Abstract','ปีที่เผยแพร่':'Publication year','ไฟล์ PDF':'PDF file','แท็ก':'Tags','ชื่อ':'Name','ชื่อเรื่อง':'Title','หัวข้อ':'Heading','คำอธิบาย':'Description','เนื้อหา':'Content','ภาพปก':'Cover image','วันที่เผยแพร่':'Publication date','สถานะ':'Status','ลำดับ':'Order','รูปภาพ':'Image','ตำแหน่ง':'Position','หน่วยงาน':'Organization','อีเมล':'Email','โทรศัพท์':'Phone','เว็บไซต์':'Website','ค้นหา':'Search','ไทย':'Thai','หน้าแรก':'Home','เกี่ยวกับสมาคม':'About','รูปภาพการ์ดหน้าแรก':'Homepage card images','ภาพการ์ดงานวิจัย':'Research card image','ภาพการ์ดเกี่ยวกับ RISA':'About RISA card image',
 'อัปโหลดหรือเลือกภาพสำหรับผลงานนี้ หากไม่ใส่ภาพจะแสดงเฉพาะข้อความ':'Upload or choose an image for this entry. Without an image, only text is shown.','คั่นชื่อด้วยเครื่องหมายจุลภาค':'Separate names with commas','คั่นแต่ละแท็กด้วยเครื่องหมายจุลภาค (,)':'Separate tags with commas','ยังไม่มีไฟล์ในคลัง — อัปโหลดไฟล์แรกได้เลย':'No files yet — upload your first file','คลังไฟล์ / Media library':'Media library','ข้อความในหน้าเว็บ':'Page content',
};
export function translateAdmin(text:string,language:'th'|'en'):string {
 if(language==='th')return text;
 if(translations[text])return translations[text];
 const suffix=text.match(/^(.*) \((ไทย|English)\)$/);
 if(suffix)return `${translations[suffix[1]]||suffix[1]} (${suffix[2]==='ไทย'?'Thai':'English'})`;
 for(const [prefix,en] of [['เพิ่ม','Add '],['แก้ไข','Edit '],['ยังไม่มี','No ']] as const){if(text.startsWith(prefix)&&translations[text.slice(prefix.length)])return en+translations[text.slice(prefix.length)];}
 return text;
}
const Context=createContext({language:'th' as 'th'|'en'});
export function useAdminLanguage(){const {language}=useContext(Context);return {language,t:(text:string)=>translateAdmin(text,language)};}
export function AdminText({children}:{children:string}){const {t}=useAdminLanguage();return <>{t(children)}</>;}
export function AdminLanguage({initial,children}:{initial:'th'|'en';children:React.ReactNode}){
 const [language,setLanguage]=useState(initial);
 useEffect(()=>{document.cookie=`risa_admin_language=${language}; Path=/admin; Max-Age=31536000; SameSite=Lax`;},[language]);
 function choose(value:'th'|'en'){setLanguage(value);}
 return <Context.Provider value={{language}}><div lang={language} className="risa-admin min-h-screen bg-paper text-ink">
  <div role="group" aria-label="Admin language" className="fixed bottom-4 right-4 z-[100] flex gap-1 rounded-lg border border-line bg-paper p-1 shadow-lg">
   {(['th','en'] as const).map(value=><button key={value} type="button" aria-pressed={language===value} onClick={()=>choose(value)} className={`rounded px-3 py-2 text-sm ${language===value?'bg-ink text-white':'text-ink'}`}>{value==='th'?'ไทย':'English'}</button>)}
  </div>{children}
 </div></Context.Provider>;
}
